import json
import os
import tempfile
import unittest
from pathlib import Path
from typing import cast

from tools.project import BuildConfig

from tools.project import Object, ProgressCategory, ProjectConfig, generate_objdiff_config


class ModuleScopedObjectTests(unittest.TestCase):
    def test_duplicate_rel_autogenerated_names_resolve_per_module(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            src_dir = root / "src"
            (src_dir / "alpha").mkdir(parents=True)
            (src_dir / "beta").mkdir(parents=True)
            (src_dir / "alpha" / "auto.c").write_text("void alpha_fn(void) {}\n")
            (src_dir / "beta" / "auto.c").write_text("void beta_fn(void) {}\n")

            config = ProjectConfig()
            config.src_dir = src_dir
            config.build_dir = root / "build"
            config.version = "TEST"
            config.asm_dir = None
            config.progress_categories = [ProgressCategory("game", "Game")]
            config.libs = [
                {
                    "lib": "alpha",
                    "mw_version": "GC/1.3.2",
                    "cflags": [],
                    "progress_category": "game",
                    "objects": [
                        Object(True, "alpha/auto", source="alpha/auto.c"),
                    ],
                },
                {
                    "lib": "beta",
                    "mw_version": "GC/1.3.2",
                    "cflags": [],
                    "progress_category": "game",
                    "objects": [
                        Object(True, "beta/auto", source="beta/auto.c"),
                    ],
                },
            ]
            objects = config.objects()
            build_config = {
                "name": "main",
                "module_id": 0,
                "ldscript": "main.ld",
                "entry": "_start",
                "units": [],
                "modules": [
                    {
                        "name": "alpha",
                        "module_id": 1,
                        "ldscript": "alpha.ld",
                        "entry": "_start",
                        "units": [
                            {"object": "alpha/auto.o", "name": "auto", "autogenerated": True}
                        ],
                    },
                    {
                        "name": "beta",
                        "module_id": 2,
                        "ldscript": "beta.ld",
                        "entry": "_start",
                        "units": [
                            {"object": "beta/auto.o", "name": "auto", "autogenerated": True}
                        ],
                    },
                ],
                "links": [],
                "version": "1.0.0",
            }

            old_cwd = os.getcwd()
            try:
                os.chdir(root)
                generate_objdiff_config(config, objects, cast(BuildConfig, build_config))
            finally:
                os.chdir(old_cwd)

            units = json.loads((root / "objdiff.json").read_text())["units"]
            by_name = {unit["name"]: unit for unit in units}
            self.assertEqual(set(by_name), {"alpha/auto", "beta/auto"})
            self.assertEqual(
                by_name["alpha/auto"]["metadata"]["source_path"],
                str(src_dir / "alpha" / "auto.c"),
            )
            self.assertEqual(
                by_name["beta/auto"]["metadata"]["source_path"],
                str(src_dir / "beta" / "auto.c"),
            )
            self.assertNotEqual(
                by_name["alpha/auto"]["base_path"], by_name["beta/auto"]["base_path"]
            )


if __name__ == "__main__":
    unittest.main()
