#!/usr/bin/env python3
"""Add public mission metrics to an objdiff v2 progress report.

The original objdiff measures remain untouched and are exposed as ``diagnostic``.
Two additional categories are derived from report functions and committed source:

* ``natural-c``: non-asm functions, with exact byte matches counted strictly.
* ``c-expressed``: non-asm functions with source bodies, with fuzzy progress
  retained as a supplemental view.

This script needs only the public checkout, report JSON, and source files. It
never reads a DOL, private cache, supervisor state, or local environment path.
"""
import argparse
import copy
import json
import re
import sys
from pathlib import Path

try:
    import natc_asmforms
except ModuleNotFoundError as exc:  # pragma: no cover - packaging failure
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    try:
        import natc_asmforms
    except ModuleNotFoundError:
        raise SystemExit(
            "decomp_report requires tools/natc_asmforms.py; refusing to emit "
            "a report with the old asm false positives") from exc

ASM_DEF = re.compile(
    r"(?<!extern\s)\b(?:static\s+)?asm\s+(?:static\s+)?"
    r"[A-Za-z_][\w \t*]*?\b(\w+)\s*\(", re.MULTILINE,
)
GAP_NAME = re.compile(r"^(?:gap_|pad_)|_pad(?:$|_)", re.IGNORECASE)


def asm_names(path):
    if not path or not path.exists():
        return set()
    return {m.group(1) for m in ASM_DEF.finditer(path.read_text(errors="replace"))}


def source_asm_forms(path):
    """Return source C definitions and forms excluded from the C lanes.

    A C signature does not make an asm-only body natural C. A hybrid with a
    bounded inline-asm statement is an additive completion lane rather than
    natural C. Keep this report on the same classifier as natc_metrics.
    """
    if not path or not path.exists():
        raise SystemExit(
            f"report unit source is missing: {path}; refusing to count "
            "target-only names as natural C")
    text = path.read_text(errors="replace")
    clean = natc_asmforms._strip_comments(text)
    # c_function_ranges intentionally stays a small source-shape parser. The
    # report has one additional, harmless wrapper around C definitions:
    # `__declspec(section ".init")`. Remove that annotation before asking the
    # shared parser for positive C definitions; asm definitions remain excluded
    # by `asm` below.
    c_text = natc_asmforms.strip_declspec(clean)
    asm = natc_asmforms.asm_defs(c_text)
    c_defs = {name for name, _start, _end in
              natc_asmforms.c_function_ranges(c_text)} - asm
    wrappers, hybrids = natc_asmforms.classify_inline_asm(c_text)
    return c_defs, asm, wrappers, hybrids


def number(value):
    return float(value or 0)


def measures(functions, total_code, total_functions, total_units, total_data=0, fuzzy=False,
             complete_units=0):
    """Return a complete objdiff ``Measures`` object for a function subset.

    decomp.dev accepts the full objdiff v2 Measures schema.  Categories are
    still calculated against the whole binary so their percentages remain
    comparable, but every standard field is emitted rather than relying on
    protobuf/JSON defaults.
    """
    matched_code = 0.0
    complete_code = 0
    matched_functions = 0
    for f in functions:
        size = int(f.get("size", 0) or 0)
        pct = number(f.get("fuzzy_match_percent"))
        if fuzzy:
            matched_code += size * pct / 100.0
        elif pct >= 100.0:
            matched_code += size
        if pct >= 100.0:
            complete_code += size
            matched_functions += 1
    matched_code = int(round(matched_code))
    code_pct = round(100.0 * matched_code / total_code, 5) if total_code else 100.0
    fn_pct = round(100.0 * matched_functions / total_functions, 5) if total_functions else 100.0
    return {
        "fuzzy_match_percent": code_pct,
        "total_code": str(total_code),
        "matched_code": str(matched_code),
        "matched_code_percent": code_pct,
        "total_data": str(total_data),
        "matched_data": "0",
        "matched_data_percent": 100.0 if not total_data else 0.0,
        "total_functions": total_functions,
        "matched_functions": matched_functions,
        "matched_functions_percent": fn_pct,
        "complete_code": str(complete_code),
        "complete_code_percent": round(100.0 * complete_code / total_code, 5) if total_code else 100.0,
        "complete_data": "0",
        "complete_data_percent": 100.0 if not total_data else 0.0,
        "total_units": total_units,
        # complete_units is a UNIT count. It used to be assigned
        # matched_functions, which published complete_units=285 against
        # total_units=215 -> 132.5581%, a figure no consumer can accept.
        #
        # There is deliberately no "complete_units_percent" here. It is NOT a
        # field of objdiff.report.Measures, and objdiff-core's deserializer is
        # generated by pbjson, which rejects unknown fields outright. Emitting
        # it made every report unparseable, so decomp.dev went on serving the
        # last one it could read (2026-08-26 to 2026-09-06) while CI stayed
        # green. Consumers derive the percentage themselves. validate_schema()
        # below now refuses to write a report carrying any such field.
        "complete_units": complete_units,
    }


def eligible_units(report, root):
    """One pass over the report: per unit, the functions that count as C.

    A function counts when it has a name, is not a gap or padding symbol, and
    is not defined with an `asm` body in the unit's source. Also records
    whether the unit is fully converted (a source exists and nothing in it is
    still asm) and which objdiff progress categories it belongs to.
    """
    units = []
    for unit in report.get("units", []):
        metadata = unit.get("metadata", {}) or {}
        source = metadata.get("source_path")
        if not source:
            # Data/coarse units can legitimately have no source. They are not
            # evidence of a C conversion and must not enter these categories.
            continue
        c_defs, names, wrappers, hybrids = source_asm_forms(root / source)
        excluded = names | wrappers | hybrids
        functions = []
        for function in unit.get("functions", []):
            name = function.get("name", "")
            if (not name or GAP_NAME.search(name) or name not in c_defs
                    or name in excluded):
                continue
            functions.append(function)
        if not functions:
            continue
        units.append({
            "functions": functions,
            "module_name": metadata.get("module_name"),
            # A unit counts toward complete_units only if it is FULLY
            # converted. Scoring "every ELIGIBLE function matched" instead put
            # 139 of 215 units in the complete column on a binary that was
            # 13.3 % done, because a unit whose one converted function matched
            # counted as finished with twenty asm bodies still beside it. The
            # honest count on the same tree was 35. A unit with no source_path
            # has converted nothing and can never be complete.
            "fully_c": bool(source) and not excluded,
            "categories": list(metadata.get("progress_categories") or []),
        })
    return units


def category_measures(units, totals, fuzzy=False):
    """Mission measures for a set of units against a fixed denominator.

    `totals` supplies total_code / total_data / total_functions / total_units,
    so percentages stay comparable with whatever objdiff reported for the same
    scope -- the whole binary for the headline, the category's own totals for
    a progress category.
    """
    functions = [f for u in units for f in u["functions"]]
    complete_units = sum(
        1 for u in units
        if u["fully_c"] and all(number(f.get("fuzzy_match_percent")) >= 100.0
                                for f in u["functions"]))
    return measures(
        functions,
        int(totals.get("total_code", 0) or 0),
        int(totals.get("total_functions", 0) or 0),
        int(totals.get("total_units", 0) or 0),
        int(totals.get("total_data", 0) or 0),
        fuzzy=fuzzy,
        complete_units=complete_units,
    )


def module_totals(report):
    """Return objdiff denominators grouped by executable module.

    The report's headline is only whole-game if it includes both the DOL and
    every REL.  Objdiff records that ownership on unit metadata, so derive
    module denominators from the units rather than maintaining a second list
    of module names in this reporting layer.
    """
    grouped = {}
    for unit in report.get("units", []):
        module = (unit.get("metadata", {}) or {}).get("module_name")
        if not module:
            continue
        totals = grouped.setdefault(module, {
            "total_code": 0,
            "total_data": 0,
            "total_functions": 0,
            "total_units": 0,
        })
        measures = unit.get("measures", {}) or {}
        totals["total_code"] += int(measures.get("total_code", 0) or 0)
        totals["total_functions"] += int(measures.get("total_functions", 0) or 0)
        totals["total_units"] += int(measures.get("total_units", 0) or 0)
        for section in unit.get("sections", []):
            if section.get("name") in {".data", ".rodata", ".sdata", ".sdata2",
                                        ".dtors", ".bss", ".sbss", ".sbss2"}:
                totals["total_data"] += int(section.get("size", 0) or 0)
    return grouped


def build_categories(report, root):
    units = eligible_units(report, root)
    totals = report.get("measures", {})
    categories = [
        {"id": "diagnostic", "name": "Diagnostic objdiff",
         "measures": copy.deepcopy(totals)},
        {"id": "natural-c", "name": "Exact natural C",
         "measures": category_measures(units, totals)},
        {"id": "c-expressed", "name": "C-expressed (fuzzy supplemental)",
         "measures": category_measures(units, totals, fuzzy=True)},
    ]
    # objdiff's own progress categories (configure.py's progress_category, eg
    # game vs sdk) are kept, because decomp.dev filters the unit list by these
    # ids. They are re-measured the way the headline is measured rather than
    # passed through: a "game 90.8 %" row taken from objdiff's fuzzy numbers
    # sitting beside a "natural-c 13.3 %" headline is the same binary counted
    # two different ways. Denominators stay objdiff's, so the reading is "N of
    # every function in game code is exact natural C".
    for upstream in report.get("categories", []):
        cid = upstream.get("id")
        if not cid or cid in {"diagnostic", "natural-c", "c-expressed"}:
            continue
        scoped = [u for u in units if cid in u["categories"]]
        categories.append({
            "id": cid,
            "name": upstream.get("name", cid),
            "measures": category_measures(scoped, upstream.get("measures", {})),
        })
    # Publish one additive row per executable module.  In particular, this
    # makes the DOL and every REL visible instead of allowing an aggregate
    # "modules" row to conceal an omitted REL.  The headline remains the
    # whole-report natural-C measure above it.
    for module, totals in sorted(module_totals(report).items()):
        scoped = [u for u in units
                  if (u.get("module_name") == module)]
        categories.append({
            "id": f"module-{module}",
            "name": f"Module {module}",
            "measures": category_measures(scoped, totals),
        })
    return categories


def source_backed_data_measures(report):
    """Count matching data only from source-backed objdiff units."""
    total_data = int(report.get("measures", {}).get("total_data", 0) or 0)
    matched_data = 0
    data_sections = {".data", ".rodata", ".sdata", ".sdata2", ".dtors", ".bss", ".sbss", ".sbss2"}
    for unit in report.get("units", []):
        if not unit.get("metadata", {}).get("source_path"):
            continue
        for section in unit.get("sections", []):
            if section.get("name") not in data_sections:
                continue
            size = int(section.get("size", 0) or 0)
            if float(section.get("fuzzy_match_percent", 0) or 0) >= 100.0:
                matched_data += size
    matched_data = min(matched_data, total_data)
    percent = round(100.0 * matched_data / total_data, 5) if total_data else 100.0
    return {
        "total_data": str(total_data),
        "matched_data": str(matched_data),
        "matched_data_percent": percent,
        "complete_data": str(matched_data),
        "complete_data_percent": percent,
    }


def apply_mission_headline(report, categories):
    """Make decomp.dev's headline the honest mission metric.

    Keep objdiff's diagnostic measures untouched and publish source-backed,
    byte-weighted data progress in the mission headline.
    """
    natural = next(c["measures"] for c in categories if c["id"] == "natural-c")
    natural.update(source_backed_data_measures(report))
    report["measures"] = natural


# objdiff.report.Measures, protos/report.proto (report version 2). decomp.dev
# parses reports with objdiff-core, whose pbjson-generated deserializer fails
# on any field not listed here -- and a failed parse is silent: the site keeps
# the previous report and CI still reports success.
MEASURE_FIELDS = frozenset({
    "fuzzy_match_percent", "total_code", "matched_code", "matched_code_percent",
    "total_data", "matched_data", "matched_data_percent", "total_functions",
    "matched_functions", "matched_functions_percent", "complete_code",
    "complete_code_percent", "complete_data", "complete_data_percent",
    "total_units", "complete_units",
})


def validate_schema(report):
    """Refuse to write a report decomp.dev would reject.

    Fail the build here rather than upload an artifact that no consumer can
    read. Raises SystemExit with the offending path and field.
    """
    def check(measures, where):
        extra = sorted(set(measures) - MEASURE_FIELDS)
        if extra:
            raise SystemExit(
                f"{where}: field(s) {', '.join(extra)} are not in "
                "objdiff.report.Measures; decomp.dev would refuse this report"
            )

    check(report.get("measures", {}), "measures")
    for category in report.get("categories", []):
        check(category.get("measures", {}), f"categories[{category.get('id')}].measures")
    for unit in report.get("units", []):
        check(unit.get("measures", {}), f"units[{unit.get('name')}].measures")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True, type=Path)
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()
    report = json.loads(args.report.read_text())
    if report.get("version") != 2:
        raise SystemExit("expected objdiff report version 2")
    categories = build_categories(report, args.root)
    report["categories"] = categories
    apply_mission_headline(report, categories)
    validate_schema(report)
    args.out.write_text(json.dumps(report, indent=2) + "\n")


if __name__ == "__main__":
    main()
